<?php
/**
 * SOC Cache Manager View
 *
 * @package Shopperexpress
 */

defined( 'ABSPATH' ) || exit;

$status_labels = array(
	'valid'   => array(
		'label' => 'Valid',
		'class' => 'soc-badge--ok',
	),
	'stale'   => array(
		'label' => 'Stale',
		'class' => 'soc-badge--warn',
	),
	'expired' => array(
		'label' => 'Expired',
		'class' => 'soc-badge--fail',
	),
	'missing' => array(
		'label' => 'Missing',
		'class' => 'soc-badge--neutral',
	),
);
?>

<div id="soc-action-notice" class="soc-notice" role="alert"></div>

<!-- 1. Cache Layers -->
<?php if ( ! empty( $data['cache_layers'] ) ) : ?>
	<div class="soc-section">
		<div class="soc-section__title"><?php esc_html_e( 'Cache Layers', 'shopperexpress' ); ?></div>
		<div class="soc-grid">
			<?php foreach ( $data['cache_layers'] as $layer ) : ?>
				<div class="soc-card">
					<div class="soc-card__label"><?php echo esc_html( $layer['name'] ); ?></div>
					<div class="soc-card__value" style="font-size:14px; padding-top:4px;">
						<?php if ( ! empty( $layer['active'] ) ) : ?>
							<span class="soc-badge soc-badge--ok"><?php esc_html_e( 'Active', 'shopperexpress' ); ?></span>
						<?php else : ?>
							<span class="soc-badge soc-badge--neutral"><?php esc_html_e( 'Inactive', 'shopperexpress' ); ?></span>
						<?php endif; ?>
					</div>
					<?php if ( ! empty( $layer['description'] ) ) : ?>
						<div class="soc-card__sub"><?php echo esc_html( $layer['description'] ); ?></div>
					<?php endif; ?>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
<?php endif; ?>

<!-- 2. Stats -->
<div class="soc-section">
	<div class="soc-section__title"><?php esc_html_e( 'Cache Stats', 'shopperexpress' ); ?></div>
	<div class="soc-grid">
		<div class="soc-card">
			<div class="soc-card__label"><?php esc_html_e( 'Object Cache', 'shopperexpress' ); ?></div>
			<div class="soc-card__value" style="font-size:14px; padding-top:4px;">
				<?php
				echo $data['object_cache_active']
					? '<span class="soc-badge soc-badge--ok">' . esc_html__( 'Active', 'shopperexpress' ) . '</span>'
					: '<span class="soc-badge soc-badge--neutral">' . esc_html__( 'Inactive', 'shopperexpress' ) . '</span>';
				?>
			</div>
		</div>
		<div class="soc-card">
			<div class="soc-card__label"><?php esc_html_e( 'Transients (total)', 'shopperexpress' ); ?></div>
			<div class="soc-card__value"><?php echo esc_html( $data['transient_count'] ?? 0 ); ?></div>
		</div>
		<div class="soc-card">
			<div class="soc-card__label"><?php esc_html_e( 'API Cache', 'shopperexpress' ); ?></div>
			<div class="soc-card__value" style="font-size:14px; padding-top:4px;">
				<?php
				echo ! empty( $data['api_cache_enabled'] )
					? '<span class="soc-badge soc-badge--ok">' . esc_html__( 'Enabled', 'shopperexpress' ) . '</span>'
					: '<span class="soc-badge soc-badge--fail">' . esc_html__( 'Disabled', 'shopperexpress' ) . '</span>';
				?>
			</div>
		</div>
		<div class="soc-card">
			<div class="soc-card__label"><?php esc_html_e( 'Last Purge', 'shopperexpress' ); ?></div>
			<div class="soc-card__value" style="font-size:14px; padding-top:4px;">
				<?php echo esc_html( $data['last_purge'] ?? __( 'Never', 'shopperexpress' ) ); ?>
			</div>
		</div>
	</div>
</div>

<!-- 3. Post Type Cache Overview -->
<div class="soc-section">
	<div class="soc-section__title">
		<?php esc_html_e( 'Post Type Cache Overview', 'shopperexpress' ); ?>
	</div>

	<?php if ( ! empty( $data['post_type_caches'] ) ) : ?>
		<table class="soc-table">
			<thead>
				<tr>
					<th><?php esc_html_e( 'Post Type', 'shopperexpress' ); ?></th>
					<th><?php esc_html_e( 'Status', 'shopperexpress' ); ?></th>
					<th><?php esc_html_e( 'Last Generated', 'shopperexpress' ); ?></th>
					<th><?php esc_html_e( 'Generated By', 'shopperexpress' ); ?></th>
					<th><?php esc_html_e( 'Actions', 'shopperexpress' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach ( $data['post_type_caches'] as $pt ) :
					$st       = $pt['status'] ?? 'missing';
					$badge    = $status_labels[ $st ] ?? $status_labels['missing'];
					$ts       = $pt['last_generated'] ? strtotime( $pt['last_generated'] ) : 0;
					$age_secs = $ts ? max( 0, current_time( 'timestamp' ) - $ts ) : 0;
					$ago      = $ts ? human_time_diff( $ts, current_time( 'timestamp' ) ) . ' ' . __( 'ago', 'shopperexpress' ) : '—';
					?>
					<tr>
						<td>
							<strong><?php echo esc_html( $pt['label'] ); ?></strong>
							<br><code style="font-size:11px;"><?php echo esc_html( $pt['post_type'] ); ?></code>
							<br><a href="<?php echo esc_url( rest_url( 'v1/vehicles/' . $pt['post_type'] ) ); ?>"
									target="_blank"
									style="font-size:11px;">
								<?php echo esc_html( rest_url( 'v1/vehicles/' . $pt['post_type'] ) ); ?>
							</a>
						</td>
						<td>
							<span class="soc-badge <?php echo esc_attr( $badge['class'] ); ?>">
								<?php echo esc_html( $badge['label'] ); ?>
							</span>
						</td>
						<td class="soc-pt-generated" data-age="<?php echo esc_attr( (string) $age_secs ); ?>">
							<?php echo esc_html( $ago ); ?>
						</td>
						<td class="soc-pt-generated-by">
							<?php
							$generated_by = $pt['generated_by'] ?? 'after import';
							if ( in_array( $st, array( 'expired', 'missing' ), true ) ) :
								?>
								<span style="color:#8c8f94;">—</span>
							<?php elseif ( $generated_by === 'after import' ) : ?>
								<span style="color:#8c8f94;font-style:italic;"><?php esc_html_e( 'after import', 'shopperexpress' ); ?></span>
							<?php else : ?>
								<?php echo esc_html( $generated_by ); ?>
							<?php endif; ?>
						</td>
						<td>
							<button class="button soc-regen-pt-cache"
									data-pt="<?php echo esc_attr( $pt['post_type'] ); ?>">
								<?php esc_html_e( 'Regenerate', 'shopperexpress' ); ?>
							</button>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	<?php else : ?>
		<p><?php esc_html_e( 'No cacheable post types detected.', 'shopperexpress' ); ?></p>
	<?php endif; ?>
</div>

<!-- 4. Global Actions -->
<div class="soc-section">
	<div class="soc-section__title"><?php esc_html_e( 'Global Cache Actions', 'shopperexpress' ); ?></div>
	<div class="soc-action-bar">
		<button id="soc-clear-all-cache" class="button button-primary">
			<?php esc_html_e( 'Clear All Cache', 'shopperexpress' ); ?>
		</button>
		<button id="soc-clear-object-cache" class="button">
			<?php esc_html_e( 'Clear Object Cache', 'shopperexpress' ); ?>
		</button>
		<button id="soc-clear-transients" class="button">
			<?php esc_html_e( 'Clear All Transients', 'shopperexpress' ); ?>
		</button>
	</div>
</div>

<!-- 6. Cache Activity Log -->
<?php
$cache_log    = $data['cache_log'] ?? array();
$log_per_page = 10;
$log_total    = count( $cache_log );
$log_pages    = $log_total > 0 ? (int) ceil( $log_total / $log_per_page ) : 1;
if ( ! empty( $cache_log ) ) :
	?>
	<div class="soc-section" id="soc-cache-log-section">
		<div class="soc-section__title"><?php esc_html_e( 'Cache Activity Log', 'shopperexpress' ); ?></div>
		<table class="soc-table" id="soc-cache-log-table">
			<thead>
				<tr>
					<th><?php esc_html_e( 'Time', 'shopperexpress' ); ?></th>
					<th><?php esc_html_e( 'Action', 'shopperexpress' ); ?></th>
					<th><?php esc_html_e( 'Post Type', 'shopperexpress' ); ?></th>
					<th><?php esc_html_e( 'User', 'shopperexpress' ); ?></th>
				</tr>
			</thead>
			<tbody id="soc-cache-log-body">
				<?php foreach ( array_slice( $cache_log, 0, $log_per_page ) as $entry ) : ?>
					<tr>
						<td><?php echo esc_html( $entry['time'] ?? '' ); ?></td>
						<td><?php echo esc_html( ucfirst( $entry['action'] ?? '' ) ); ?></td>
						<td><code><?php echo esc_html( $entry['post_type'] ?? '—' ); ?></code></td>
						<td><?php echo esc_html( $entry['user'] ?? '' ); ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>

		<?php if ( $log_pages > 1 ) : ?>
		<div class="soc-pagination" id="soc-log-pagination"
			data-total="<?php echo esc_attr( $log_total ); ?>"
			data-per-page="<?php echo esc_attr( $log_per_page ); ?>"
			data-pages="<?php echo esc_attr( $log_pages ); ?>"
			data-current="1">
			<button class="button soc-log-prev" disabled><?php esc_html_e( '&laquo; Prev', 'shopperexpress' ); ?></button>
			<span class="soc-pagination__info">
				<?php printf( esc_html__( 'Page %1$s of %2$s', 'shopperexpress' ), '<span id="soc-log-page-num">1</span>', esc_html( $log_pages ) ); ?>
			</span>
			<button class="button soc-log-next" <?php echo $log_pages <= 1 ? 'disabled' : ''; ?>><?php esc_html_e( 'Next &raquo;', 'shopperexpress' ); ?></button>
		</div>

		<script type="application/json" id="soc-cache-log-data">
			<?php echo wp_json_encode( $cache_log ); ?>
		</script>
		<?php endif; ?>
	</div>
<?php endif; ?>

<p class="soc-footer-note">
	<em><?php printf( esc_html__( 'Last collected: %s', 'shopperexpress' ), esc_html( $data['collected_at'] ?? 'N/A' ) ); ?></em>
</p>
