<?php
/**
 * SOC Assets
 *
 * Handles enqueueing of styles and scripts used by the SOC (Operation Center) admin pages.
 *
 * @package Shopperexpress
 */

namespace App\Components\SOC;

/**
 * Class SOC_Assets
 *
 * Responsible for registering and enqueuing styles and scripts
 * required by the operation center pages in the WordPress admin.
 */
class SOC_Assets {

	/**
	 * The current theme version, used for cache busting.
	 *
	 * @var string
	 */
	private string $theme_version;

	/**
	 * SOC_Assets constructor.
	 *
	 * Initializes the theme version used for asset versioning.
	 */
	public function __construct() {
		// Get the theme version to use for asset cache busting.
		$this->theme_version = wp_get_theme()->get( 'Version' );
	}

	/**
	 * Enqueue SOC-related styles and scripts in the admin dashboard.
	 *
	 * This method should only be called on SOC (Operation Center) admin pages
	 * and will:
	 *   - Enqueue the SOC admin stylesheet.
	 *   - Enqueue the SOC admin JavaScript.
	 *   - Localize some strings and data required by the frontend script.
	 *
	 * @return void
	 */
	public function enqueue(): void {
		$version = $this->theme_version;

		// Enqueue the SOC CSS file.
		wp_enqueue_style(
			'shopperexpress/soc',
			get_template_directory_uri() . '/assets/dist/soc.css',
			array(),
			$version
		);

		// Enqueue the SOC JavaScript file, with jQuery as dependency, load in footer.
		wp_enqueue_script(
			'shopperexpress/soc',
			get_template_directory_uri() . '/assets/dist/js/soc.js',
			array( 'jquery' ),
			$version,
			true
		);

		// Pass AJAX URL, security nonce, and some UI strings for use in the JS.
		wp_localize_script(
			'shopperexpress/soc',
			'socData',
			array(
				// URL for AJAX requests.
				'ajaxUrl'   => admin_url( 'admin-ajax.php' ),
				// Security nonce for verifying requests.
				'nonce'     => wp_create_nonce( 'soc_nonce' ),
				// Current user email — used to update "Generated By" cell after regen.
				'userEmail' => wp_get_current_user()->user_email ?: '',
				// UI strings for the frontend JS interactions.
				'strings'   => array(
					'confirm_delete' => __( 'Are you sure?', 'shopperexpress' ),
					'loading'        => __( 'Loading...', 'shopperexpress' ),
					'success'        => __( 'Done!', 'shopperexpress' ),
					'error'          => __( 'An error occurred.', 'shopperexpress' ),
				),
			)
		);
	}
}
