name: Deploy to Cloudways

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CLOUDWAYS_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.CLOUDWAYS_PORT }} ${{ secrets.CLOUDWAYS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via git pull on server
        run: |
          ssh -p ${{ secrets.CLOUDWAYS_PORT }} ${{ secrets.CLOUDWAYS_USER }}@${{ secrets.CLOUDWAYS_HOST }} '
            set -e
            cd ${{ secrets.CLOUDWAYS_PATH_STAGE }}


            echo "== Pulling latest code =="
            GIT_SSH_COMMAND="ssh -i /home/master/.ssh/id_ed25519 -o StrictHostKeyChecking=no" git -c safe.directory='*' pull origin main

            echo "== Installing composer dependencies =="
            composer install --no-dev --optimize-autoloader --no-interaction
           
            echo "== Deploy finished =="
          '